/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
)

// checks if the ChoiceInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChoiceInput{}

// ChoiceInput Make a choice in a contract
type ChoiceInput struct {
	ForChoiceId ChoiceId `json:"for_choice_id"`
	InputThatChoosesNum int32 `json:"input_that_chooses_num"`
}

// NewChoiceInput instantiates a new ChoiceInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChoiceInput(forChoiceId ChoiceId, inputThatChoosesNum int32) *ChoiceInput {
	this := ChoiceInput{}
	this.ForChoiceId = forChoiceId
	this.InputThatChoosesNum = inputThatChoosesNum
	return &this
}

// NewChoiceInputWithDefaults instantiates a new ChoiceInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChoiceInputWithDefaults() *ChoiceInput {
	this := ChoiceInput{}
	return &this
}

// GetForChoiceId returns the ForChoiceId field value
func (o *ChoiceInput) GetForChoiceId() ChoiceId {
	if o == nil {
		var ret ChoiceId
		return ret
	}

	return o.ForChoiceId
}

// GetForChoiceIdOk returns a tuple with the ForChoiceId field value
// and a boolean to check if the value has been set.
func (o *ChoiceInput) GetForChoiceIdOk() (*ChoiceId, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ForChoiceId, true
}

// SetForChoiceId sets field value
func (o *ChoiceInput) SetForChoiceId(v ChoiceId) {
	o.ForChoiceId = v
}

// GetInputThatChoosesNum returns the InputThatChoosesNum field value
func (o *ChoiceInput) GetInputThatChoosesNum() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.InputThatChoosesNum
}

// GetInputThatChoosesNumOk returns a tuple with the InputThatChoosesNum field value
// and a boolean to check if the value has been set.
func (o *ChoiceInput) GetInputThatChoosesNumOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InputThatChoosesNum, true
}

// SetInputThatChoosesNum sets field value
func (o *ChoiceInput) SetInputThatChoosesNum(v int32) {
	o.InputThatChoosesNum = v
}

func (o ChoiceInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChoiceInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["for_choice_id"] = o.ForChoiceId
	toSerialize["input_that_chooses_num"] = o.InputThatChoosesNum
	return toSerialize, nil
}

type NullableChoiceInput struct {
	value *ChoiceInput
	isSet bool
}

func (v NullableChoiceInput) Get() *ChoiceInput {
	return v.value
}

func (v *NullableChoiceInput) Set(val *ChoiceInput) {
	v.value = val
	v.isSet = true
}

func (v NullableChoiceInput) IsSet() bool {
	return v.isSet
}

func (v *NullableChoiceInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChoiceInput(val *ChoiceInput) *NullableChoiceInput {
	return &NullableChoiceInput{value: val, isSet: true}
}

func (v NullableChoiceInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChoiceInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


