/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
)

// checks if the ValueOfChoiceObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValueOfChoiceObject{}

// ValueOfChoiceObject struct for ValueOfChoiceObject
type ValueOfChoiceObject struct {
	ValueOfChoice ChoiceIdObject `json:"value_of_choice"`
}

// NewValueOfChoiceObject instantiates a new ValueOfChoiceObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValueOfChoiceObject(valueOfChoice ChoiceIdObject) *ValueOfChoiceObject {
	this := ValueOfChoiceObject{}
	this.ValueOfChoice = valueOfChoice
	return &this
}

// NewValueOfChoiceObjectWithDefaults instantiates a new ValueOfChoiceObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValueOfChoiceObjectWithDefaults() *ValueOfChoiceObject {
	this := ValueOfChoiceObject{}
	return &this
}

// GetValueOfChoice returns the ValueOfChoice field value
func (o *ValueOfChoiceObject) GetValueOfChoice() ChoiceIdObject {
	if o == nil {
		var ret ChoiceIdObject
		return ret
	}

	return o.ValueOfChoice
}

// GetValueOfChoiceOk returns a tuple with the ValueOfChoice field value
// and a boolean to check if the value has been set.
func (o *ValueOfChoiceObject) GetValueOfChoiceOk() (*ChoiceIdObject, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValueOfChoice, true
}

// SetValueOfChoice sets field value
func (o *ValueOfChoiceObject) SetValueOfChoice(v ChoiceIdObject) {
	o.ValueOfChoice = v
}

func (o ValueOfChoiceObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValueOfChoiceObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value_of_choice"] = o.ValueOfChoice
	return toSerialize, nil
}

type NullableValueOfChoiceObject struct {
	value *ValueOfChoiceObject
	isSet bool
}

func (v NullableValueOfChoiceObject) Get() *ValueOfChoiceObject {
	return v.value
}

func (v *NullableValueOfChoiceObject) Set(val *ValueOfChoiceObject) {
	v.value = val
	v.isSet = true
}

func (v NullableValueOfChoiceObject) IsSet() bool {
	return v.isSet
}

func (v *NullableValueOfChoiceObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValueOfChoiceObject(val *ValueOfChoiceObject) *NullableValueOfChoiceObject {
	return &NullableValueOfChoiceObject{value: val, isSet: true}
}

func (v NullableValueOfChoiceObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValueOfChoiceObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


