/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
)

// checks if the NonPositiveDeposit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NonPositiveDeposit{}

// NonPositiveDeposit A warning for a non-positive deposit.
type NonPositiveDeposit struct {
	AskedToDeposit int32 `json:"asked_to_deposit"`
	InAccount Party `json:"in_account"`
	OfToken Token `json:"of_token"`
	Party Party `json:"party"`
}

// NewNonPositiveDeposit instantiates a new NonPositiveDeposit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNonPositiveDeposit(askedToDeposit int32, inAccount Party, ofToken Token, party Party) *NonPositiveDeposit {
	this := NonPositiveDeposit{}
	this.AskedToDeposit = askedToDeposit
	this.InAccount = inAccount
	this.OfToken = ofToken
	this.Party = party
	return &this
}

// NewNonPositiveDepositWithDefaults instantiates a new NonPositiveDeposit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNonPositiveDepositWithDefaults() *NonPositiveDeposit {
	this := NonPositiveDeposit{}
	return &this
}

// GetAskedToDeposit returns the AskedToDeposit field value
func (o *NonPositiveDeposit) GetAskedToDeposit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AskedToDeposit
}

// GetAskedToDepositOk returns a tuple with the AskedToDeposit field value
// and a boolean to check if the value has been set.
func (o *NonPositiveDeposit) GetAskedToDepositOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AskedToDeposit, true
}

// SetAskedToDeposit sets field value
func (o *NonPositiveDeposit) SetAskedToDeposit(v int32) {
	o.AskedToDeposit = v
}

// GetInAccount returns the InAccount field value
func (o *NonPositiveDeposit) GetInAccount() Party {
	if o == nil {
		var ret Party
		return ret
	}

	return o.InAccount
}

// GetInAccountOk returns a tuple with the InAccount field value
// and a boolean to check if the value has been set.
func (o *NonPositiveDeposit) GetInAccountOk() (*Party, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InAccount, true
}

// SetInAccount sets field value
func (o *NonPositiveDeposit) SetInAccount(v Party) {
	o.InAccount = v
}

// GetOfToken returns the OfToken field value
func (o *NonPositiveDeposit) GetOfToken() Token {
	if o == nil {
		var ret Token
		return ret
	}

	return o.OfToken
}

// GetOfTokenOk returns a tuple with the OfToken field value
// and a boolean to check if the value has been set.
func (o *NonPositiveDeposit) GetOfTokenOk() (*Token, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OfToken, true
}

// SetOfToken sets field value
func (o *NonPositiveDeposit) SetOfToken(v Token) {
	o.OfToken = v
}

// GetParty returns the Party field value
func (o *NonPositiveDeposit) GetParty() Party {
	if o == nil {
		var ret Party
		return ret
	}

	return o.Party
}

// GetPartyOk returns a tuple with the Party field value
// and a boolean to check if the value has been set.
func (o *NonPositiveDeposit) GetPartyOk() (*Party, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Party, true
}

// SetParty sets field value
func (o *NonPositiveDeposit) SetParty(v Party) {
	o.Party = v
}

func (o NonPositiveDeposit) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NonPositiveDeposit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["asked_to_deposit"] = o.AskedToDeposit
	toSerialize["in_account"] = o.InAccount
	toSerialize["of_token"] = o.OfToken
	toSerialize["party"] = o.Party
	return toSerialize, nil
}

type NullableNonPositiveDeposit struct {
	value *NonPositiveDeposit
	isSet bool
}

func (v NullableNonPositiveDeposit) Get() *NonPositiveDeposit {
	return v.value
}

func (v *NullableNonPositiveDeposit) Set(val *NonPositiveDeposit) {
	v.value = val
	v.isSet = true
}

func (v NullableNonPositiveDeposit) IsSet() bool {
	return v.isSet
}

func (v *NullableNonPositiveDeposit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNonPositiveDeposit(val *NonPositiveDeposit) *NullableNonPositiveDeposit {
	return &NullableNonPositiveDeposit{value: val, isSet: true}
}

func (v NullableNonPositiveDeposit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNonPositiveDeposit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


