/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
)

// checks if the MetadataAndScript type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetadataAndScript{}

// MetadataAndScript struct for MetadataAndScript
type MetadataAndScript struct {
	Metadata *TokenMetadata `json:"metadata,omitempty"`
	// The type of script receiving the role token.
	Script string `json:"script"`
}

// NewMetadataAndScript instantiates a new MetadataAndScript object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetadataAndScript(script string) *MetadataAndScript {
	this := MetadataAndScript{}
	this.Script = script
	return &this
}

// NewMetadataAndScriptWithDefaults instantiates a new MetadataAndScript object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetadataAndScriptWithDefaults() *MetadataAndScript {
	this := MetadataAndScript{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *MetadataAndScript) GetMetadata() TokenMetadata {
	if o == nil || IsNil(o.Metadata) {
		var ret TokenMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetadataAndScript) GetMetadataOk() (*TokenMetadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *MetadataAndScript) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given TokenMetadata and assigns it to the Metadata field.
func (o *MetadataAndScript) SetMetadata(v TokenMetadata) {
	o.Metadata = &v
}

// GetScript returns the Script field value
func (o *MetadataAndScript) GetScript() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Script
}

// GetScriptOk returns a tuple with the Script field value
// and a boolean to check if the value has been set.
func (o *MetadataAndScript) GetScriptOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Script, true
}

// SetScript sets field value
func (o *MetadataAndScript) SetScript(v string) {
	o.Script = v
}

func (o MetadataAndScript) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetadataAndScript) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	toSerialize["script"] = o.Script
	return toSerialize, nil
}

type NullableMetadataAndScript struct {
	value *MetadataAndScript
	isSet bool
}

func (v NullableMetadataAndScript) Get() *MetadataAndScript {
	return v.value
}

func (v *NullableMetadataAndScript) Set(val *MetadataAndScript) {
	v.value = val
	v.isSet = true
}

func (v NullableMetadataAndScript) IsSet() bool {
	return v.isSet
}

func (v *NullableMetadataAndScript) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetadataAndScript(val *MetadataAndScript) *NullableMetadataAndScript {
	return &NullableMetadataAndScript{value: val, isSet: true}
}

func (v NullableMetadataAndScript) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetadataAndScript) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


