/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
)

// checks if the TokenInAccount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenInAccount{}

// TokenInAccount struct for TokenInAccount
type TokenInAccount struct {
	AmountOfToken Token `json:"amount_of_token"`
	InAccount Party `json:"in_account"`
}

// NewTokenInAccount instantiates a new TokenInAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenInAccount(amountOfToken Token, inAccount Party) *TokenInAccount {
	this := TokenInAccount{}
	this.AmountOfToken = amountOfToken
	this.InAccount = inAccount
	return &this
}

// NewTokenInAccountWithDefaults instantiates a new TokenInAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenInAccountWithDefaults() *TokenInAccount {
	this := TokenInAccount{}
	return &this
}

// GetAmountOfToken returns the AmountOfToken field value
func (o *TokenInAccount) GetAmountOfToken() Token {
	if o == nil {
		var ret Token
		return ret
	}

	return o.AmountOfToken
}

// GetAmountOfTokenOk returns a tuple with the AmountOfToken field value
// and a boolean to check if the value has been set.
func (o *TokenInAccount) GetAmountOfTokenOk() (*Token, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmountOfToken, true
}

// SetAmountOfToken sets field value
func (o *TokenInAccount) SetAmountOfToken(v Token) {
	o.AmountOfToken = v
}

// GetInAccount returns the InAccount field value
func (o *TokenInAccount) GetInAccount() Party {
	if o == nil {
		var ret Party
		return ret
	}

	return o.InAccount
}

// GetInAccountOk returns a tuple with the InAccount field value
// and a boolean to check if the value has been set.
func (o *TokenInAccount) GetInAccountOk() (*Party, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InAccount, true
}

// SetInAccount sets field value
func (o *TokenInAccount) SetInAccount(v Party) {
	o.InAccount = v
}

func (o TokenInAccount) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenInAccount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["amount_of_token"] = o.AmountOfToken
	toSerialize["in_account"] = o.InAccount
	return toSerialize, nil
}

type NullableTokenInAccount struct {
	value *TokenInAccount
	isSet bool
}

func (v NullableTokenInAccount) Get() *TokenInAccount {
	return v.value
}

func (v *NullableTokenInAccount) Set(val *TokenInAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenInAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenInAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenInAccount(val *TokenInAccount) *NullableTokenInAccount {
	return &NullableTokenInAccount{value: val, isSet: true}
}

func (v NullableTokenInAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenInAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


