/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
	"fmt"
)

// TransactionOutput - Marlowe transaction output.
type TransactionOutput struct {
	TxOutputError *TxOutputError
	TxOutputSuccess *TxOutputSuccess
}

// TxOutputErrorAsTransactionOutput is a convenience function that returns TxOutputError wrapped in TransactionOutput
func TxOutputErrorAsTransactionOutput(v *TxOutputError) TransactionOutput {
	return TransactionOutput{
		TxOutputError: v,
	}
}

// TxOutputSuccessAsTransactionOutput is a convenience function that returns TxOutputSuccess wrapped in TransactionOutput
func TxOutputSuccessAsTransactionOutput(v *TxOutputSuccess) TransactionOutput {
	return TransactionOutput{
		TxOutputSuccess: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *TransactionOutput) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into TxOutputError
	err = newStrictDecoder(data).Decode(&dst.TxOutputError)
	if err == nil {
		jsonTxOutputError, _ := json.Marshal(dst.TxOutputError)
		if string(jsonTxOutputError) == "{}" { // empty struct
			dst.TxOutputError = nil
		} else {
			match++
		}
	} else {
		dst.TxOutputError = nil
	}

	// try to unmarshal data into TxOutputSuccess
	err = newStrictDecoder(data).Decode(&dst.TxOutputSuccess)
	if err == nil {
		jsonTxOutputSuccess, _ := json.Marshal(dst.TxOutputSuccess)
		if string(jsonTxOutputSuccess) == "{}" { // empty struct
			dst.TxOutputSuccess = nil
		} else {
			match++
		}
	} else {
		dst.TxOutputSuccess = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.TxOutputError = nil
		dst.TxOutputSuccess = nil

		return fmt.Errorf("data matches more than one schema in oneOf(TransactionOutput)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(TransactionOutput)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src TransactionOutput) MarshalJSON() ([]byte, error) {
	if src.TxOutputError != nil {
		return json.Marshal(&src.TxOutputError)
	}

	if src.TxOutputSuccess != nil {
		return json.Marshal(&src.TxOutputSuccess)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *TransactionOutput) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.TxOutputError != nil {
		return obj.TxOutputError
	}

	if obj.TxOutputSuccess != nil {
		return obj.TxOutputSuccess
	}

	// all schemas are nil
	return nil
}

type NullableTransactionOutput struct {
	value *TransactionOutput
	isSet bool
}

func (v NullableTransactionOutput) Get() *TransactionOutput {
	return v.value
}

func (v *NullableTransactionOutput) Set(val *TransactionOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionOutput(val *TransactionOutput) *NullableTransactionOutput {
	return &NullableTransactionOutput{value: val, isSet: true}
}

func (v NullableTransactionOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


