/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
)

// checks if the PayToParty type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PayToParty{}

// PayToParty Pays funds to a party.
type PayToParty struct {
	Party Party `json:"party"`
}

// NewPayToParty instantiates a new PayToParty object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPayToParty(party Party) *PayToParty {
	this := PayToParty{}
	this.Party = party
	return &this
}

// NewPayToPartyWithDefaults instantiates a new PayToParty object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPayToPartyWithDefaults() *PayToParty {
	this := PayToParty{}
	return &this
}

// GetParty returns the Party field value
func (o *PayToParty) GetParty() Party {
	if o == nil {
		var ret Party
		return ret
	}

	return o.Party
}

// GetPartyOk returns a tuple with the Party field value
// and a boolean to check if the value has been set.
func (o *PayToParty) GetPartyOk() (*Party, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Party, true
}

// SetParty sets field value
func (o *PayToParty) SetParty(v Party) {
	o.Party = v
}

func (o PayToParty) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PayToParty) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["party"] = o.Party
	return toSerialize, nil
}

type NullablePayToParty struct {
	value *PayToParty
	isSet bool
}

func (v NullablePayToParty) Get() *PayToParty {
	return v.value
}

func (v *NullablePayToParty) Set(val *PayToParty) {
	v.value = val
	v.isSet = true
}

func (v NullablePayToParty) IsSet() bool {
	return v.isSet
}

func (v *NullablePayToParty) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePayToParty(val *PayToParty) *NullablePayToParty {
	return &NullablePayToParty{value: val, isSet: true}
}

func (v NullablePayToParty) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePayToParty) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


