/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
)

// checks if the StakingHash type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StakingHash{}

// StakingHash A Plutus staking hash.
type StakingHash struct {
	StakingHash PlutusCredential `json:"stakingHash"`
}

// NewStakingHash instantiates a new StakingHash object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStakingHash(stakingHash PlutusCredential) *StakingHash {
	this := StakingHash{}
	this.StakingHash = stakingHash
	return &this
}

// NewStakingHashWithDefaults instantiates a new StakingHash object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStakingHashWithDefaults() *StakingHash {
	this := StakingHash{}
	return &this
}

// GetStakingHash returns the StakingHash field value
func (o *StakingHash) GetStakingHash() PlutusCredential {
	if o == nil {
		var ret PlutusCredential
		return ret
	}

	return o.StakingHash
}

// GetStakingHashOk returns a tuple with the StakingHash field value
// and a boolean to check if the value has been set.
func (o *StakingHash) GetStakingHashOk() (*PlutusCredential, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StakingHash, true
}

// SetStakingHash sets field value
func (o *StakingHash) SetStakingHash(v PlutusCredential) {
	o.StakingHash = v
}

func (o StakingHash) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StakingHash) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["stakingHash"] = o.StakingHash
	return toSerialize, nil
}

type NullableStakingHash struct {
	value *StakingHash
	isSet bool
}

func (v NullableStakingHash) Get() *StakingHash {
	return v.value
}

func (v *NullableStakingHash) Set(val *StakingHash) {
	v.value = val
	v.isSet = true
}

func (v NullableStakingHash) IsSet() bool {
	return v.isSet
}

func (v *NullableStakingHash) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStakingHash(val *StakingHash) *NullableStakingHash {
	return &NullableStakingHash{value: val, isSet: true}
}

func (v NullableStakingHash) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStakingHash) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


