/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
)

// checks if the ChoiceIdObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChoiceIdObject{}

// ChoiceIdObject Refers to a party by role name.
type ChoiceIdObject struct {
	ChoiceName string `json:"choice_name"`
	ChoiceOwner PartyObject `json:"choice_owner"`
}

// NewChoiceIdObject instantiates a new ChoiceIdObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChoiceIdObject(choiceName string, choiceOwner PartyObject) *ChoiceIdObject {
	this := ChoiceIdObject{}
	this.ChoiceName = choiceName
	this.ChoiceOwner = choiceOwner
	return &this
}

// NewChoiceIdObjectWithDefaults instantiates a new ChoiceIdObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChoiceIdObjectWithDefaults() *ChoiceIdObject {
	this := ChoiceIdObject{}
	return &this
}

// GetChoiceName returns the ChoiceName field value
func (o *ChoiceIdObject) GetChoiceName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChoiceName
}

// GetChoiceNameOk returns a tuple with the ChoiceName field value
// and a boolean to check if the value has been set.
func (o *ChoiceIdObject) GetChoiceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChoiceName, true
}

// SetChoiceName sets field value
func (o *ChoiceIdObject) SetChoiceName(v string) {
	o.ChoiceName = v
}

// GetChoiceOwner returns the ChoiceOwner field value
func (o *ChoiceIdObject) GetChoiceOwner() PartyObject {
	if o == nil {
		var ret PartyObject
		return ret
	}

	return o.ChoiceOwner
}

// GetChoiceOwnerOk returns a tuple with the ChoiceOwner field value
// and a boolean to check if the value has been set.
func (o *ChoiceIdObject) GetChoiceOwnerOk() (*PartyObject, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChoiceOwner, true
}

// SetChoiceOwner sets field value
func (o *ChoiceIdObject) SetChoiceOwner(v PartyObject) {
	o.ChoiceOwner = v
}

func (o ChoiceIdObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChoiceIdObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["choice_name"] = o.ChoiceName
	toSerialize["choice_owner"] = o.ChoiceOwner
	return toSerialize, nil
}

type NullableChoiceIdObject struct {
	value *ChoiceIdObject
	isSet bool
}

func (v NullableChoiceIdObject) Get() *ChoiceIdObject {
	return v.value
}

func (v *NullableChoiceIdObject) Set(val *ChoiceIdObject) {
	v.value = val
	v.isSet = true
}

func (v NullableChoiceIdObject) IsSet() bool {
	return v.isSet
}

func (v *NullableChoiceIdObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChoiceIdObject(val *ChoiceIdObject) *NullableChoiceIdObject {
	return &NullableChoiceIdObject{value: val, isSet: true}
}

func (v NullableChoiceIdObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChoiceIdObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


