/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
)

// checks if the IntervalInPastIntervalInPastError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntervalInPastIntervalInPastError{}

// IntervalInPastIntervalInPastError struct for IntervalInPastIntervalInPastError
type IntervalInPastIntervalInPastError struct {
	From int32 `json:"from"`
	MinTime int32 `json:"minTime"`
	To int32 `json:"to"`
}

// NewIntervalInPastIntervalInPastError instantiates a new IntervalInPastIntervalInPastError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntervalInPastIntervalInPastError(from int32, minTime int32, to int32) *IntervalInPastIntervalInPastError {
	this := IntervalInPastIntervalInPastError{}
	this.From = from
	this.MinTime = minTime
	this.To = to
	return &this
}

// NewIntervalInPastIntervalInPastErrorWithDefaults instantiates a new IntervalInPastIntervalInPastError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntervalInPastIntervalInPastErrorWithDefaults() *IntervalInPastIntervalInPastError {
	this := IntervalInPastIntervalInPastError{}
	return &this
}

// GetFrom returns the From field value
func (o *IntervalInPastIntervalInPastError) GetFrom() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *IntervalInPastIntervalInPastError) GetFromOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *IntervalInPastIntervalInPastError) SetFrom(v int32) {
	o.From = v
}

// GetMinTime returns the MinTime field value
func (o *IntervalInPastIntervalInPastError) GetMinTime() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MinTime
}

// GetMinTimeOk returns a tuple with the MinTime field value
// and a boolean to check if the value has been set.
func (o *IntervalInPastIntervalInPastError) GetMinTimeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinTime, true
}

// SetMinTime sets field value
func (o *IntervalInPastIntervalInPastError) SetMinTime(v int32) {
	o.MinTime = v
}

// GetTo returns the To field value
func (o *IntervalInPastIntervalInPastError) GetTo() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *IntervalInPastIntervalInPastError) GetToOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *IntervalInPastIntervalInPastError) SetTo(v int32) {
	o.To = v
}

func (o IntervalInPastIntervalInPastError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntervalInPastIntervalInPastError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["from"] = o.From
	toSerialize["minTime"] = o.MinTime
	toSerialize["to"] = o.To
	return toSerialize, nil
}

type NullableIntervalInPastIntervalInPastError struct {
	value *IntervalInPastIntervalInPastError
	isSet bool
}

func (v NullableIntervalInPastIntervalInPastError) Get() *IntervalInPastIntervalInPastError {
	return v.value
}

func (v *NullableIntervalInPastIntervalInPastError) Set(val *IntervalInPastIntervalInPastError) {
	v.value = val
	v.isSet = true
}

func (v NullableIntervalInPastIntervalInPastError) IsSet() bool {
	return v.isSet
}

func (v *NullableIntervalInPastIntervalInPastError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntervalInPastIntervalInPastError(val *IntervalInPastIntervalInPastError) *NullableIntervalInPastIntervalInPastError {
	return &NullableIntervalInPastIntervalInPastError{value: val, isSet: true}
}

func (v NullableIntervalInPastIntervalInPastError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntervalInPastIntervalInPastError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


