/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
)

// checks if the Pay type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Pay{}

// Pay A payment will be sent from an account to a payee.
type Pay struct {
	FromAccount Party `json:"from_account"`
	Pay Value `json:"pay"`
	Then Contract `json:"then"`
	To Payee `json:"to"`
	Token Token `json:"token"`
}

// NewPay instantiates a new Pay object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPay(fromAccount Party, pay Value, then Contract, to Payee, token Token) *Pay {
	this := Pay{}
	this.FromAccount = fromAccount
	this.Pay = pay
	this.Then = then
	this.To = to
	this.Token = token
	return &this
}

// NewPayWithDefaults instantiates a new Pay object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPayWithDefaults() *Pay {
	this := Pay{}
	return &this
}

// GetFromAccount returns the FromAccount field value
func (o *Pay) GetFromAccount() Party {
	if o == nil {
		var ret Party
		return ret
	}

	return o.FromAccount
}

// GetFromAccountOk returns a tuple with the FromAccount field value
// and a boolean to check if the value has been set.
func (o *Pay) GetFromAccountOk() (*Party, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FromAccount, true
}

// SetFromAccount sets field value
func (o *Pay) SetFromAccount(v Party) {
	o.FromAccount = v
}

// GetPay returns the Pay field value
func (o *Pay) GetPay() Value {
	if o == nil {
		var ret Value
		return ret
	}

	return o.Pay
}

// GetPayOk returns a tuple with the Pay field value
// and a boolean to check if the value has been set.
func (o *Pay) GetPayOk() (*Value, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pay, true
}

// SetPay sets field value
func (o *Pay) SetPay(v Value) {
	o.Pay = v
}

// GetThen returns the Then field value
func (o *Pay) GetThen() Contract {
	if o == nil {
		var ret Contract
		return ret
	}

	return o.Then
}

// GetThenOk returns a tuple with the Then field value
// and a boolean to check if the value has been set.
func (o *Pay) GetThenOk() (*Contract, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Then, true
}

// SetThen sets field value
func (o *Pay) SetThen(v Contract) {
	o.Then = v
}

// GetTo returns the To field value
func (o *Pay) GetTo() Payee {
	if o == nil {
		var ret Payee
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *Pay) GetToOk() (*Payee, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *Pay) SetTo(v Payee) {
	o.To = v
}

// GetToken returns the Token field value
func (o *Pay) GetToken() Token {
	if o == nil {
		var ret Token
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *Pay) GetTokenOk() (*Token, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *Pay) SetToken(v Token) {
	o.Token = v
}

func (o Pay) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Pay) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["from_account"] = o.FromAccount
	toSerialize["pay"] = o.Pay
	toSerialize["then"] = o.Then
	toSerialize["to"] = o.To
	toSerialize["token"] = o.Token
	return toSerialize, nil
}

type NullablePay struct {
	value *Pay
	isSet bool
}

func (v NullablePay) Get() *Pay {
	return v.value
}

func (v *NullablePay) Set(val *Pay) {
	v.value = val
	v.isSet = true
}

func (v NullablePay) IsSet() bool {
	return v.isSet
}

func (v *NullablePay) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePay(val *Pay) *NullablePay {
	return &NullablePay{value: val, isSet: true}
}

func (v NullablePay) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePay) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


