/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
)

// checks if the Assert type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Assert{}

// Assert Check an observation and produce a warning if it is false.
type Assert struct {
	Assert Observation `json:"assert"`
	Then Contract `json:"then"`
}

// NewAssert instantiates a new Assert object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssert(assert Observation, then Contract) *Assert {
	this := Assert{}
	this.Assert = assert
	this.Then = then
	return &this
}

// NewAssertWithDefaults instantiates a new Assert object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssertWithDefaults() *Assert {
	this := Assert{}
	return &this
}

// GetAssert returns the Assert field value
func (o *Assert) GetAssert() Observation {
	if o == nil {
		var ret Observation
		return ret
	}

	return o.Assert
}

// GetAssertOk returns a tuple with the Assert field value
// and a boolean to check if the value has been set.
func (o *Assert) GetAssertOk() (*Observation, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Assert, true
}

// SetAssert sets field value
func (o *Assert) SetAssert(v Observation) {
	o.Assert = v
}

// GetThen returns the Then field value
func (o *Assert) GetThen() Contract {
	if o == nil {
		var ret Contract
		return ret
	}

	return o.Then
}

// GetThenOk returns a tuple with the Then field value
// and a boolean to check if the value has been set.
func (o *Assert) GetThenOk() (*Contract, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Then, true
}

// SetThen sets field value
func (o *Assert) SetThen(v Contract) {
	o.Then = v
}

func (o Assert) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Assert) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["assert"] = o.Assert
	toSerialize["then"] = o.Then
	return toSerialize, nil
}

type NullableAssert struct {
	value *Assert
	isSet bool
}

func (v NullableAssert) Get() *Assert {
	return v.value
}

func (v *NullableAssert) Set(val *Assert) {
	v.value = val
	v.isSet = true
}

func (v NullableAssert) IsSet() bool {
	return v.isSet
}

func (v *NullableAssert) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssert(val *Assert) *NullableAssert {
	return &NullableAssert{value: val, isSet: true}
}

func (v NullableAssert) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssert) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


