/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
	"fmt"
)

// TokenObject - A token with a currency symbol (minting policy ID) and token name.
type TokenObject struct {
	LabelRef *LabelRef
	Token *Token
}

// LabelRefAsTokenObject is a convenience function that returns LabelRef wrapped in TokenObject
func LabelRefAsTokenObject(v *LabelRef) TokenObject {
	return TokenObject{
		LabelRef: v,
	}
}

// TokenAsTokenObject is a convenience function that returns Token wrapped in TokenObject
func TokenAsTokenObject(v *Token) TokenObject {
	return TokenObject{
		Token: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *TokenObject) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into LabelRef
	err = newStrictDecoder(data).Decode(&dst.LabelRef)
	if err == nil {
		jsonLabelRef, _ := json.Marshal(dst.LabelRef)
		if string(jsonLabelRef) == "{}" { // empty struct
			dst.LabelRef = nil
		} else {
			match++
		}
	} else {
		dst.LabelRef = nil
	}

	// try to unmarshal data into Token
	err = newStrictDecoder(data).Decode(&dst.Token)
	if err == nil {
		jsonToken, _ := json.Marshal(dst.Token)
		if string(jsonToken) == "{}" { // empty struct
			dst.Token = nil
		} else {
			match++
		}
	} else {
		dst.Token = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.LabelRef = nil
		dst.Token = nil

		return fmt.Errorf("data matches more than one schema in oneOf(TokenObject)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(TokenObject)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src TokenObject) MarshalJSON() ([]byte, error) {
	if src.LabelRef != nil {
		return json.Marshal(&src.LabelRef)
	}

	if src.Token != nil {
		return json.Marshal(&src.Token)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *TokenObject) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.LabelRef != nil {
		return obj.LabelRef
	}

	if obj.Token != nil {
		return obj.Token
	}

	// all schemas are nil
	return nil
}

type NullableTokenObject struct {
	value *TokenObject
	isSet bool
}

func (v NullableTokenObject) Get() *TokenObject {
	return v.value
}

func (v *NullableTokenObject) Set(val *TokenObject) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenObject) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenObject(val *TokenObject) *NullableTokenObject {
	return &NullableTokenObject{value: val, isSet: true}
}

func (v NullableTokenObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


