/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
)

// checks if the OrObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrObject{}

// OrObject struct for OrObject
type OrObject struct {
	Either ObservationObject `json:"either"`
	Or ObservationObject `json:"or"`
}

// NewOrObject instantiates a new OrObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrObject(either ObservationObject, or ObservationObject) *OrObject {
	this := OrObject{}
	this.Either = either
	this.Or = or
	return &this
}

// NewOrObjectWithDefaults instantiates a new OrObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrObjectWithDefaults() *OrObject {
	this := OrObject{}
	return &this
}

// GetEither returns the Either field value
func (o *OrObject) GetEither() ObservationObject {
	if o == nil {
		var ret ObservationObject
		return ret
	}

	return o.Either
}

// GetEitherOk returns a tuple with the Either field value
// and a boolean to check if the value has been set.
func (o *OrObject) GetEitherOk() (*ObservationObject, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Either, true
}

// SetEither sets field value
func (o *OrObject) SetEither(v ObservationObject) {
	o.Either = v
}

// GetOr returns the Or field value
func (o *OrObject) GetOr() ObservationObject {
	if o == nil {
		var ret ObservationObject
		return ret
	}

	return o.Or
}

// GetOrOk returns a tuple with the Or field value
// and a boolean to check if the value has been set.
func (o *OrObject) GetOrOk() (*ObservationObject, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Or, true
}

// SetOr sets field value
func (o *OrObject) SetOr(v ObservationObject) {
	o.Or = v
}

func (o OrObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["either"] = o.Either
	toSerialize["or"] = o.Or
	return toSerialize, nil
}

type NullableOrObject struct {
	value *OrObject
	isSet bool
}

func (v NullableOrObject) Get() *OrObject {
	return v.value
}

func (v *NullableOrObject) Set(val *OrObject) {
	v.value = val
	v.isSet = true
}

func (v NullableOrObject) IsSet() bool {
	return v.isSet
}

func (v *NullableOrObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrObject(val *OrObject) *NullableOrObject {
	return &NullableOrObject{value: val, isSet: true}
}

func (v NullableOrObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


