/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
)

// checks if the GetTransactionsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetTransactionsResponse{}

// GetTransactionsResponse struct for GetTransactionsResponse
type GetTransactionsResponse struct {
	Results []GetTransactionsResponseResultsInner `json:"results"`
}

// NewGetTransactionsResponse instantiates a new GetTransactionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTransactionsResponse(results []GetTransactionsResponseResultsInner) *GetTransactionsResponse {
	this := GetTransactionsResponse{}
	this.Results = results
	return &this
}

// NewGetTransactionsResponseWithDefaults instantiates a new GetTransactionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTransactionsResponseWithDefaults() *GetTransactionsResponse {
	this := GetTransactionsResponse{}
	return &this
}

// GetResults returns the Results field value
func (o *GetTransactionsResponse) GetResults() []GetTransactionsResponseResultsInner {
	if o == nil {
		var ret []GetTransactionsResponseResultsInner
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *GetTransactionsResponse) GetResultsOk() ([]GetTransactionsResponseResultsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *GetTransactionsResponse) SetResults(v []GetTransactionsResponseResultsInner) {
	o.Results = v
}

func (o GetTransactionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetTransactionsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["results"] = o.Results
	return toSerialize, nil
}

type NullableGetTransactionsResponse struct {
	value *GetTransactionsResponse
	isSet bool
}

func (v NullableGetTransactionsResponse) Get() *GetTransactionsResponse {
	return v.value
}

func (v *NullableGetTransactionsResponse) Set(val *GetTransactionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTransactionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTransactionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTransactionsResponse(val *GetTransactionsResponse) *NullableGetTransactionsResponse {
	return &NullableGetTransactionsResponse{value: val, isSet: true}
}

func (v NullableGetTransactionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTransactionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


