/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
)

// checks if the Multiply type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Multiply{}

// Multiply struct for Multiply
type Multiply struct {
	Multiply Value `json:"multiply"`
	Times Value `json:"times"`
}

// NewMultiply instantiates a new Multiply object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMultiply(multiply Value, times Value) *Multiply {
	this := Multiply{}
	this.Multiply = multiply
	this.Times = times
	return &this
}

// NewMultiplyWithDefaults instantiates a new Multiply object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMultiplyWithDefaults() *Multiply {
	this := Multiply{}
	return &this
}

// GetMultiply returns the Multiply field value
func (o *Multiply) GetMultiply() Value {
	if o == nil {
		var ret Value
		return ret
	}

	return o.Multiply
}

// GetMultiplyOk returns a tuple with the Multiply field value
// and a boolean to check if the value has been set.
func (o *Multiply) GetMultiplyOk() (*Value, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Multiply, true
}

// SetMultiply sets field value
func (o *Multiply) SetMultiply(v Value) {
	o.Multiply = v
}

// GetTimes returns the Times field value
func (o *Multiply) GetTimes() Value {
	if o == nil {
		var ret Value
		return ret
	}

	return o.Times
}

// GetTimesOk returns a tuple with the Times field value
// and a boolean to check if the value has been set.
func (o *Multiply) GetTimesOk() (*Value, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Times, true
}

// SetTimes sets field value
func (o *Multiply) SetTimes(v Value) {
	o.Times = v
}

func (o Multiply) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Multiply) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["multiply"] = o.Multiply
	toSerialize["times"] = o.Times
	return toSerialize, nil
}

type NullableMultiply struct {
	value *Multiply
	isSet bool
}

func (v NullableMultiply) Get() *Multiply {
	return v.value
}

func (v *NullableMultiply) Set(val *Multiply) {
	v.value = val
	v.isSet = true
}

func (v NullableMultiply) IsSet() bool {
	return v.isSet
}

func (v *NullableMultiply) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMultiply(val *Multiply) *NullableMultiply {
	return &NullableMultiply{value: val, isSet: true}
}

func (v NullableMultiply) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMultiply) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


