/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
)

// checks if the And type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &And{}

// And struct for And
type And struct {
	And Observation `json:"and"`
	Both Observation `json:"both"`
}

// NewAnd instantiates a new And object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnd(and Observation, both Observation) *And {
	this := And{}
	this.And = and
	this.Both = both
	return &this
}

// NewAndWithDefaults instantiates a new And object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAndWithDefaults() *And {
	this := And{}
	return &this
}

// GetAnd returns the And field value
func (o *And) GetAnd() Observation {
	if o == nil {
		var ret Observation
		return ret
	}

	return o.And
}

// GetAndOk returns a tuple with the And field value
// and a boolean to check if the value has been set.
func (o *And) GetAndOk() (*Observation, bool) {
	if o == nil {
		return nil, false
	}
	return &o.And, true
}

// SetAnd sets field value
func (o *And) SetAnd(v Observation) {
	o.And = v
}

// GetBoth returns the Both field value
func (o *And) GetBoth() Observation {
	if o == nil {
		var ret Observation
		return ret
	}

	return o.Both
}

// GetBothOk returns a tuple with the Both field value
// and a boolean to check if the value has been set.
func (o *And) GetBothOk() (*Observation, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Both, true
}

// SetBoth sets field value
func (o *And) SetBoth(v Observation) {
	o.Both = v
}

func (o And) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o And) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["and"] = o.And
	toSerialize["both"] = o.Both
	return toSerialize, nil
}

type NullableAnd struct {
	value *And
	isSet bool
}

func (v NullableAnd) Get() *And {
	return v.value
}

func (v *NullableAnd) Set(val *And) {
	v.value = val
	v.isSet = true
}

func (v NullableAnd) IsSet() bool {
	return v.isSet
}

func (v *NullableAnd) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnd(val *And) *NullableAnd {
	return &NullableAnd{value: val, isSet: true}
}

func (v NullableAnd) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnd) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


