/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
)

// checks if the AssertObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssertObject{}

// AssertObject Check an observation and produce a warning if it is false.
type AssertObject struct {
	Assert ObservationObject `json:"assert"`
	Then ContractObject `json:"then"`
}

// NewAssertObject instantiates a new AssertObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssertObject(assert ObservationObject, then ContractObject) *AssertObject {
	this := AssertObject{}
	this.Assert = assert
	this.Then = then
	return &this
}

// NewAssertObjectWithDefaults instantiates a new AssertObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssertObjectWithDefaults() *AssertObject {
	this := AssertObject{}
	return &this
}

// GetAssert returns the Assert field value
func (o *AssertObject) GetAssert() ObservationObject {
	if o == nil {
		var ret ObservationObject
		return ret
	}

	return o.Assert
}

// GetAssertOk returns a tuple with the Assert field value
// and a boolean to check if the value has been set.
func (o *AssertObject) GetAssertOk() (*ObservationObject, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Assert, true
}

// SetAssert sets field value
func (o *AssertObject) SetAssert(v ObservationObject) {
	o.Assert = v
}

// GetThen returns the Then field value
func (o *AssertObject) GetThen() ContractObject {
	if o == nil {
		var ret ContractObject
		return ret
	}

	return o.Then
}

// GetThenOk returns a tuple with the Then field value
// and a boolean to check if the value has been set.
func (o *AssertObject) GetThenOk() (*ContractObject, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Then, true
}

// SetThen sets field value
func (o *AssertObject) SetThen(v ContractObject) {
	o.Then = v
}

func (o AssertObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssertObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["assert"] = o.Assert
	toSerialize["then"] = o.Then
	return toSerialize, nil
}

type NullableAssertObject struct {
	value *AssertObject
	isSet bool
}

func (v NullableAssertObject) Get() *AssertObject {
	return v.value
}

func (v *NullableAssertObject) Set(val *AssertObject) {
	v.value = val
	v.isSet = true
}

func (v NullableAssertObject) IsSet() bool {
	return v.isSet
}

func (v *NullableAssertObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssertObject(val *AssertObject) *NullableAssertObject {
	return &NullableAssertObject{value: val, isSet: true}
}

func (v NullableAssertObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssertObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


