/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
)

// checks if the PubKeyCredential type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PubKeyCredential{}

// PubKeyCredential A Plutus public key credential.
type PubKeyCredential struct {
	PubKeyCredential string `json:"pubKeyCredential"`
}

// NewPubKeyCredential instantiates a new PubKeyCredential object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPubKeyCredential(pubKeyCredential string) *PubKeyCredential {
	this := PubKeyCredential{}
	this.PubKeyCredential = pubKeyCredential
	return &this
}

// NewPubKeyCredentialWithDefaults instantiates a new PubKeyCredential object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPubKeyCredentialWithDefaults() *PubKeyCredential {
	this := PubKeyCredential{}
	return &this
}

// GetPubKeyCredential returns the PubKeyCredential field value
func (o *PubKeyCredential) GetPubKeyCredential() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PubKeyCredential
}

// GetPubKeyCredentialOk returns a tuple with the PubKeyCredential field value
// and a boolean to check if the value has been set.
func (o *PubKeyCredential) GetPubKeyCredentialOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PubKeyCredential, true
}

// SetPubKeyCredential sets field value
func (o *PubKeyCredential) SetPubKeyCredential(v string) {
	o.PubKeyCredential = v
}

func (o PubKeyCredential) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PubKeyCredential) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pubKeyCredential"] = o.PubKeyCredential
	return toSerialize, nil
}

type NullablePubKeyCredential struct {
	value *PubKeyCredential
	isSet bool
}

func (v NullablePubKeyCredential) Get() *PubKeyCredential {
	return v.value
}

func (v *NullablePubKeyCredential) Set(val *PubKeyCredential) {
	v.value = val
	v.isSet = true
}

func (v NullablePubKeyCredential) IsSet() bool {
	return v.isSet
}

func (v *NullablePubKeyCredential) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePubKeyCredential(val *PubKeyCredential) *NullablePubKeyCredential {
	return &NullablePubKeyCredential{value: val, isSet: true}
}

func (v NullablePubKeyCredential) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePubKeyCredential) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


