/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
)

// checks if the ExBudget type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExBudget{}

// ExBudget struct for ExBudget
type ExBudget struct {
	ExBudgetCPU float32 `json:"exBudgetCPU"`
	ExBudgetMemory float32 `json:"exBudgetMemory"`
}

// NewExBudget instantiates a new ExBudget object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExBudget(exBudgetCPU float32, exBudgetMemory float32) *ExBudget {
	this := ExBudget{}
	this.ExBudgetCPU = exBudgetCPU
	this.ExBudgetMemory = exBudgetMemory
	return &this
}

// NewExBudgetWithDefaults instantiates a new ExBudget object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExBudgetWithDefaults() *ExBudget {
	this := ExBudget{}
	return &this
}

// GetExBudgetCPU returns the ExBudgetCPU field value
func (o *ExBudget) GetExBudgetCPU() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ExBudgetCPU
}

// GetExBudgetCPUOk returns a tuple with the ExBudgetCPU field value
// and a boolean to check if the value has been set.
func (o *ExBudget) GetExBudgetCPUOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExBudgetCPU, true
}

// SetExBudgetCPU sets field value
func (o *ExBudget) SetExBudgetCPU(v float32) {
	o.ExBudgetCPU = v
}

// GetExBudgetMemory returns the ExBudgetMemory field value
func (o *ExBudget) GetExBudgetMemory() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ExBudgetMemory
}

// GetExBudgetMemoryOk returns a tuple with the ExBudgetMemory field value
// and a boolean to check if the value has been set.
func (o *ExBudget) GetExBudgetMemoryOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExBudgetMemory, true
}

// SetExBudgetMemory sets field value
func (o *ExBudget) SetExBudgetMemory(v float32) {
	o.ExBudgetMemory = v
}

func (o ExBudget) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExBudget) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["exBudgetCPU"] = o.ExBudgetCPU
	toSerialize["exBudgetMemory"] = o.ExBudgetMemory
	return toSerialize, nil
}

type NullableExBudget struct {
	value *ExBudget
	isSet bool
}

func (v NullableExBudget) Get() *ExBudget {
	return v.value
}

func (v *NullableExBudget) Set(val *ExBudget) {
	v.value = val
	v.isSet = true
}

func (v NullableExBudget) IsSet() bool {
	return v.isSet
}

func (v *NullableExBudget) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExBudget(val *ExBudget) *NullableExBudget {
	return &NullableExBudget{value: val, isSet: true}
}

func (v NullableExBudget) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExBudget) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


