/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
)

// checks if the ScriptCredential type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScriptCredential{}

// ScriptCredential A Plutus script credential.
type ScriptCredential struct {
	ScriptCredential string `json:"scriptCredential"`
}

// NewScriptCredential instantiates a new ScriptCredential object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScriptCredential(scriptCredential string) *ScriptCredential {
	this := ScriptCredential{}
	this.ScriptCredential = scriptCredential
	return &this
}

// NewScriptCredentialWithDefaults instantiates a new ScriptCredential object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScriptCredentialWithDefaults() *ScriptCredential {
	this := ScriptCredential{}
	return &this
}

// GetScriptCredential returns the ScriptCredential field value
func (o *ScriptCredential) GetScriptCredential() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ScriptCredential
}

// GetScriptCredentialOk returns a tuple with the ScriptCredential field value
// and a boolean to check if the value has been set.
func (o *ScriptCredential) GetScriptCredentialOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScriptCredential, true
}

// SetScriptCredential sets field value
func (o *ScriptCredential) SetScriptCredential(v string) {
	o.ScriptCredential = v
}

func (o ScriptCredential) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScriptCredential) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["scriptCredential"] = o.ScriptCredential
	return toSerialize, nil
}

type NullableScriptCredential struct {
	value *ScriptCredential
	isSet bool
}

func (v NullableScriptCredential) Get() *ScriptCredential {
	return v.value
}

func (v *NullableScriptCredential) Set(val *ScriptCredential) {
	v.value = val
	v.isSet = true
}

func (v NullableScriptCredential) IsSet() bool {
	return v.isSet
}

func (v *NullableScriptCredential) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScriptCredential(val *ScriptCredential) *NullableScriptCredential {
	return &NullableScriptCredential{value: val, isSet: true}
}

func (v NullableScriptCredential) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScriptCredential) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


