/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
	"fmt"
)

// Case - A contract which becomes active when an action occurs.
type Case struct {
	CaseMerkleizedThen *CaseMerkleizedThen
	CaseThen *CaseThen
}

// CaseMerkleizedThenAsCase is a convenience function that returns CaseMerkleizedThen wrapped in Case
func CaseMerkleizedThenAsCase(v *CaseMerkleizedThen) Case {
	return Case{
		CaseMerkleizedThen: v,
	}
}

// CaseThenAsCase is a convenience function that returns CaseThen wrapped in Case
func CaseThenAsCase(v *CaseThen) Case {
	return Case{
		CaseThen: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *Case) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into CaseMerkleizedThen
	err = newStrictDecoder(data).Decode(&dst.CaseMerkleizedThen)
	if err == nil {
		jsonCaseMerkleizedThen, _ := json.Marshal(dst.CaseMerkleizedThen)
		if string(jsonCaseMerkleizedThen) == "{}" { // empty struct
			dst.CaseMerkleizedThen = nil
		} else {
			match++
		}
	} else {
		dst.CaseMerkleizedThen = nil
	}

	// try to unmarshal data into CaseThen
	err = newStrictDecoder(data).Decode(&dst.CaseThen)
	if err == nil {
		jsonCaseThen, _ := json.Marshal(dst.CaseThen)
		if string(jsonCaseThen) == "{}" { // empty struct
			dst.CaseThen = nil
		} else {
			match++
		}
	} else {
		dst.CaseThen = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CaseMerkleizedThen = nil
		dst.CaseThen = nil

		return fmt.Errorf("data matches more than one schema in oneOf(Case)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(Case)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Case) MarshalJSON() ([]byte, error) {
	if src.CaseMerkleizedThen != nil {
		return json.Marshal(&src.CaseMerkleizedThen)
	}

	if src.CaseThen != nil {
		return json.Marshal(&src.CaseThen)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *Case) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.CaseMerkleizedThen != nil {
		return obj.CaseMerkleizedThen
	}

	if obj.CaseThen != nil {
		return obj.CaseThen
	}

	// all schemas are nil
	return nil
}

type NullableCase struct {
	value *Case
	isSet bool
}

func (v NullableCase) Get() *Case {
	return v.value
}

func (v *NullableCase) Set(val *Case) {
	v.value = val
	v.isSet = true
}

func (v NullableCase) IsSet() bool {
	return v.isSet
}

func (v *NullableCase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCase(val *Case) *NullableCase {
	return &NullableCase{value: val, isSet: true}
}

func (v NullableCase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


