/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
)

// checks if the LetObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LetObject{}

// LetObject Bind a value to a name within the scope of a sub-contract.
type LetObject struct {
	Be ValueObject `json:"be"`
	Let string `json:"let"`
	Then ContractObject `json:"then"`
}

// NewLetObject instantiates a new LetObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLetObject(be ValueObject, let string, then ContractObject) *LetObject {
	this := LetObject{}
	this.Be = be
	this.Let = let
	this.Then = then
	return &this
}

// NewLetObjectWithDefaults instantiates a new LetObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLetObjectWithDefaults() *LetObject {
	this := LetObject{}
	return &this
}

// GetBe returns the Be field value
func (o *LetObject) GetBe() ValueObject {
	if o == nil {
		var ret ValueObject
		return ret
	}

	return o.Be
}

// GetBeOk returns a tuple with the Be field value
// and a boolean to check if the value has been set.
func (o *LetObject) GetBeOk() (*ValueObject, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Be, true
}

// SetBe sets field value
func (o *LetObject) SetBe(v ValueObject) {
	o.Be = v
}

// GetLet returns the Let field value
func (o *LetObject) GetLet() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Let
}

// GetLetOk returns a tuple with the Let field value
// and a boolean to check if the value has been set.
func (o *LetObject) GetLetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Let, true
}

// SetLet sets field value
func (o *LetObject) SetLet(v string) {
	o.Let = v
}

// GetThen returns the Then field value
func (o *LetObject) GetThen() ContractObject {
	if o == nil {
		var ret ContractObject
		return ret
	}

	return o.Then
}

// GetThenOk returns a tuple with the Then field value
// and a boolean to check if the value has been set.
func (o *LetObject) GetThenOk() (*ContractObject, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Then, true
}

// SetThen sets field value
func (o *LetObject) SetThen(v ContractObject) {
	o.Then = v
}

func (o LetObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LetObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["be"] = o.Be
	toSerialize["let"] = o.Let
	toSerialize["then"] = o.Then
	return toSerialize, nil
}

type NullableLetObject struct {
	value *LetObject
	isSet bool
}

func (v NullableLetObject) Get() *LetObject {
	return v.value
}

func (v *NullableLetObject) Set(val *LetObject) {
	v.value = val
	v.isSet = true
}

func (v NullableLetObject) IsSet() bool {
	return v.isSet
}

func (v *NullableLetObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLetObject(val *LetObject) *NullableLetObject {
	return &NullableLetObject{value: val, isSet: true}
}

func (v NullableLetObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLetObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


