/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
)

// checks if the CreateTxBodyEnvelope type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTxBodyEnvelope{}

// CreateTxBodyEnvelope The \"type\" property of \"txBody\" must be \"TxBody BabbageEra\" or \"TxBody ConwayEra\"
type CreateTxBodyEnvelope struct {
	// A reference to a transaction output with a transaction ID and index.
	ContractId string `json:"contractId"`
	SafetyErrors []SafetyError `json:"safetyErrors,omitempty"`
	TxBody TextEnvelope `json:"txBody"`
}

// NewCreateTxBodyEnvelope instantiates a new CreateTxBodyEnvelope object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTxBodyEnvelope(contractId string, txBody TextEnvelope) *CreateTxBodyEnvelope {
	this := CreateTxBodyEnvelope{}
	this.ContractId = contractId
	this.TxBody = txBody
	return &this
}

// NewCreateTxBodyEnvelopeWithDefaults instantiates a new CreateTxBodyEnvelope object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTxBodyEnvelopeWithDefaults() *CreateTxBodyEnvelope {
	this := CreateTxBodyEnvelope{}
	return &this
}

// GetContractId returns the ContractId field value
func (o *CreateTxBodyEnvelope) GetContractId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContractId
}

// GetContractIdOk returns a tuple with the ContractId field value
// and a boolean to check if the value has been set.
func (o *CreateTxBodyEnvelope) GetContractIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContractId, true
}

// SetContractId sets field value
func (o *CreateTxBodyEnvelope) SetContractId(v string) {
	o.ContractId = v
}

// GetSafetyErrors returns the SafetyErrors field value if set, zero value otherwise.
func (o *CreateTxBodyEnvelope) GetSafetyErrors() []SafetyError {
	if o == nil || IsNil(o.SafetyErrors) {
		var ret []SafetyError
		return ret
	}
	return o.SafetyErrors
}

// GetSafetyErrorsOk returns a tuple with the SafetyErrors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTxBodyEnvelope) GetSafetyErrorsOk() ([]SafetyError, bool) {
	if o == nil || IsNil(o.SafetyErrors) {
		return nil, false
	}
	return o.SafetyErrors, true
}

// HasSafetyErrors returns a boolean if a field has been set.
func (o *CreateTxBodyEnvelope) HasSafetyErrors() bool {
	if o != nil && !IsNil(o.SafetyErrors) {
		return true
	}

	return false
}

// SetSafetyErrors gets a reference to the given []SafetyError and assigns it to the SafetyErrors field.
func (o *CreateTxBodyEnvelope) SetSafetyErrors(v []SafetyError) {
	o.SafetyErrors = v
}

// GetTxBody returns the TxBody field value
func (o *CreateTxBodyEnvelope) GetTxBody() TextEnvelope {
	if o == nil {
		var ret TextEnvelope
		return ret
	}

	return o.TxBody
}

// GetTxBodyOk returns a tuple with the TxBody field value
// and a boolean to check if the value has been set.
func (o *CreateTxBodyEnvelope) GetTxBodyOk() (*TextEnvelope, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TxBody, true
}

// SetTxBody sets field value
func (o *CreateTxBodyEnvelope) SetTxBody(v TextEnvelope) {
	o.TxBody = v
}

func (o CreateTxBodyEnvelope) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTxBodyEnvelope) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["contractId"] = o.ContractId
	if !IsNil(o.SafetyErrors) {
		toSerialize["safetyErrors"] = o.SafetyErrors
	}
	toSerialize["txBody"] = o.TxBody
	return toSerialize, nil
}

type NullableCreateTxBodyEnvelope struct {
	value *CreateTxBodyEnvelope
	isSet bool
}

func (v NullableCreateTxBodyEnvelope) Get() *CreateTxBodyEnvelope {
	return v.value
}

func (v *NullableCreateTxBodyEnvelope) Set(val *CreateTxBodyEnvelope) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTxBodyEnvelope) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTxBodyEnvelope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTxBodyEnvelope(val *CreateTxBodyEnvelope) *NullableCreateTxBodyEnvelope {
	return &NullableCreateTxBodyEnvelope{value: val, isSet: true}
}

func (v NullableCreateTxBodyEnvelope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTxBodyEnvelope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


