/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
	"fmt"
)

// PlutusStakingCredential - A Plutus staking credential.
type PlutusStakingCredential struct {
	StakingHash *StakingHash
	StakingPointer *StakingPointer
}

// StakingHashAsPlutusStakingCredential is a convenience function that returns StakingHash wrapped in PlutusStakingCredential
func StakingHashAsPlutusStakingCredential(v *StakingHash) PlutusStakingCredential {
	return PlutusStakingCredential{
		StakingHash: v,
	}
}

// StakingPointerAsPlutusStakingCredential is a convenience function that returns StakingPointer wrapped in PlutusStakingCredential
func StakingPointerAsPlutusStakingCredential(v *StakingPointer) PlutusStakingCredential {
	return PlutusStakingCredential{
		StakingPointer: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PlutusStakingCredential) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into StakingHash
	err = newStrictDecoder(data).Decode(&dst.StakingHash)
	if err == nil {
		jsonStakingHash, _ := json.Marshal(dst.StakingHash)
		if string(jsonStakingHash) == "{}" { // empty struct
			dst.StakingHash = nil
		} else {
			match++
		}
	} else {
		dst.StakingHash = nil
	}

	// try to unmarshal data into StakingPointer
	err = newStrictDecoder(data).Decode(&dst.StakingPointer)
	if err == nil {
		jsonStakingPointer, _ := json.Marshal(dst.StakingPointer)
		if string(jsonStakingPointer) == "{}" { // empty struct
			dst.StakingPointer = nil
		} else {
			match++
		}
	} else {
		dst.StakingPointer = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.StakingHash = nil
		dst.StakingPointer = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PlutusStakingCredential)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PlutusStakingCredential)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PlutusStakingCredential) MarshalJSON() ([]byte, error) {
	if src.StakingHash != nil {
		return json.Marshal(&src.StakingHash)
	}

	if src.StakingPointer != nil {
		return json.Marshal(&src.StakingPointer)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PlutusStakingCredential) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.StakingHash != nil {
		return obj.StakingHash
	}

	if obj.StakingPointer != nil {
		return obj.StakingPointer
	}

	// all schemas are nil
	return nil
}

type NullablePlutusStakingCredential struct {
	value *PlutusStakingCredential
	isSet bool
}

func (v NullablePlutusStakingCredential) Get() *PlutusStakingCredential {
	return v.value
}

func (v *NullablePlutusStakingCredential) Set(val *PlutusStakingCredential) {
	v.value = val
	v.isSet = true
}

func (v NullablePlutusStakingCredential) IsSet() bool {
	return v.isSet
}

func (v *NullablePlutusStakingCredential) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlutusStakingCredential(val *PlutusStakingCredential) *NullablePlutusStakingCredential {
	return &NullablePlutusStakingCredential{value: val, isSet: true}
}

func (v NullablePlutusStakingCredential) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlutusStakingCredential) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


