/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
)

// checks if the Lesser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Lesser{}

// Lesser struct for Lesser
type Lesser struct {
	Lt Value `json:"lt"`
	Value Value `json:"value"`
}

// NewLesser instantiates a new Lesser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLesser(lt Value, value Value) *Lesser {
	this := Lesser{}
	this.Lt = lt
	this.Value = value
	return &this
}

// NewLesserWithDefaults instantiates a new Lesser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLesserWithDefaults() *Lesser {
	this := Lesser{}
	return &this
}

// GetLt returns the Lt field value
func (o *Lesser) GetLt() Value {
	if o == nil {
		var ret Value
		return ret
	}

	return o.Lt
}

// GetLtOk returns a tuple with the Lt field value
// and a boolean to check if the value has been set.
func (o *Lesser) GetLtOk() (*Value, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Lt, true
}

// SetLt sets field value
func (o *Lesser) SetLt(v Value) {
	o.Lt = v
}

// GetValue returns the Value field value
func (o *Lesser) GetValue() Value {
	if o == nil {
		var ret Value
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *Lesser) GetValueOk() (*Value, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *Lesser) SetValue(v Value) {
	o.Value = v
}

func (o Lesser) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Lesser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["lt"] = o.Lt
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

type NullableLesser struct {
	value *Lesser
	isSet bool
}

func (v NullableLesser) Get() *Lesser {
	return v.value
}

func (v *NullableLesser) Set(val *Lesser) {
	v.value = val
	v.isSet = true
}

func (v NullableLesser) IsSet() bool {
	return v.isSet
}

func (v *NullableLesser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLesser(val *Lesser) *NullableLesser {
	return &NullableLesser{value: val, isSet: true}
}

func (v NullableLesser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLesser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


