/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
)

// checks if the CaseThenObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CaseThenObject{}

// CaseThenObject struct for CaseThenObject
type CaseThenObject struct {
	Case ActionObject `json:"case"`
	Then ContractObject `json:"then"`
}

// NewCaseThenObject instantiates a new CaseThenObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCaseThenObject(case_ ActionObject, then ContractObject) *CaseThenObject {
	this := CaseThenObject{}
	this.Case = case_
	this.Then = then
	return &this
}

// NewCaseThenObjectWithDefaults instantiates a new CaseThenObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCaseThenObjectWithDefaults() *CaseThenObject {
	this := CaseThenObject{}
	return &this
}

// GetCase returns the Case field value
func (o *CaseThenObject) GetCase() ActionObject {
	if o == nil {
		var ret ActionObject
		return ret
	}

	return o.Case
}

// GetCaseOk returns a tuple with the Case field value
// and a boolean to check if the value has been set.
func (o *CaseThenObject) GetCaseOk() (*ActionObject, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Case, true
}

// SetCase sets field value
func (o *CaseThenObject) SetCase(v ActionObject) {
	o.Case = v
}

// GetThen returns the Then field value
func (o *CaseThenObject) GetThen() ContractObject {
	if o == nil {
		var ret ContractObject
		return ret
	}

	return o.Then
}

// GetThenOk returns a tuple with the Then field value
// and a boolean to check if the value has been set.
func (o *CaseThenObject) GetThenOk() (*ContractObject, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Then, true
}

// SetThen sets field value
func (o *CaseThenObject) SetThen(v ContractObject) {
	o.Then = v
}

func (o CaseThenObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CaseThenObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["case"] = o.Case
	toSerialize["then"] = o.Then
	return toSerialize, nil
}

type NullableCaseThenObject struct {
	value *CaseThenObject
	isSet bool
}

func (v NullableCaseThenObject) Get() *CaseThenObject {
	return v.value
}

func (v *NullableCaseThenObject) Set(val *CaseThenObject) {
	v.value = val
	v.isSet = true
}

func (v NullableCaseThenObject) IsSet() bool {
	return v.isSet
}

func (v *NullableCaseThenObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCaseThenObject(val *CaseThenObject) *NullableCaseThenObject {
	return &NullableCaseThenObject{value: val, isSet: true}
}

func (v NullableCaseThenObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCaseThenObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


