/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
)

// checks if the ChooseForObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChooseForObject{}

// ChooseForObject struct for ChooseForObject
type ChooseForObject struct {
	ChoseSomethingFor ChoiceIdObject `json:"chose_something_for"`
}

// NewChooseForObject instantiates a new ChooseForObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChooseForObject(choseSomethingFor ChoiceIdObject) *ChooseForObject {
	this := ChooseForObject{}
	this.ChoseSomethingFor = choseSomethingFor
	return &this
}

// NewChooseForObjectWithDefaults instantiates a new ChooseForObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChooseForObjectWithDefaults() *ChooseForObject {
	this := ChooseForObject{}
	return &this
}

// GetChoseSomethingFor returns the ChoseSomethingFor field value
func (o *ChooseForObject) GetChoseSomethingFor() ChoiceIdObject {
	if o == nil {
		var ret ChoiceIdObject
		return ret
	}

	return o.ChoseSomethingFor
}

// GetChoseSomethingForOk returns a tuple with the ChoseSomethingFor field value
// and a boolean to check if the value has been set.
func (o *ChooseForObject) GetChoseSomethingForOk() (*ChoiceIdObject, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChoseSomethingFor, true
}

// SetChoseSomethingFor sets field value
func (o *ChooseForObject) SetChoseSomethingFor(v ChoiceIdObject) {
	o.ChoseSomethingFor = v
}

func (o ChooseForObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChooseForObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["chose_something_for"] = o.ChoseSomethingFor
	return toSerialize, nil
}

type NullableChooseForObject struct {
	value *ChooseForObject
	isSet bool
}

func (v NullableChooseForObject) Get() *ChooseForObject {
	return v.value
}

func (v *NullableChooseForObject) Set(val *ChooseForObject) {
	v.value = val
	v.isSet = true
}

func (v NullableChooseForObject) IsSet() bool {
	return v.isSet
}

func (v *NullableChooseForObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChooseForObject(val *ChooseForObject) *NullableChooseForObject {
	return &NullableChooseForObject{value: val, isSet: true}
}

func (v NullableChooseForObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChooseForObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


