/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
)

// checks if the GetTransactionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetTransactionResponse{}

// GetTransactionResponse struct for GetTransactionResponse
type GetTransactionResponse struct {
	Links GetTransactionResponseLinks `json:"links"`
	Resource Tx `json:"resource"`
}

// NewGetTransactionResponse instantiates a new GetTransactionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTransactionResponse(links GetTransactionResponseLinks, resource Tx) *GetTransactionResponse {
	this := GetTransactionResponse{}
	this.Links = links
	this.Resource = resource
	return &this
}

// NewGetTransactionResponseWithDefaults instantiates a new GetTransactionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTransactionResponseWithDefaults() *GetTransactionResponse {
	this := GetTransactionResponse{}
	return &this
}

// GetLinks returns the Links field value
func (o *GetTransactionResponse) GetLinks() GetTransactionResponseLinks {
	if o == nil {
		var ret GetTransactionResponseLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *GetTransactionResponse) GetLinksOk() (*GetTransactionResponseLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *GetTransactionResponse) SetLinks(v GetTransactionResponseLinks) {
	o.Links = v
}

// GetResource returns the Resource field value
func (o *GetTransactionResponse) GetResource() Tx {
	if o == nil {
		var ret Tx
		return ret
	}

	return o.Resource
}

// GetResourceOk returns a tuple with the Resource field value
// and a boolean to check if the value has been set.
func (o *GetTransactionResponse) GetResourceOk() (*Tx, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Resource, true
}

// SetResource sets field value
func (o *GetTransactionResponse) SetResource(v Tx) {
	o.Resource = v
}

func (o GetTransactionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetTransactionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["links"] = o.Links
	toSerialize["resource"] = o.Resource
	return toSerialize, nil
}

type NullableGetTransactionResponse struct {
	value *GetTransactionResponse
	isSet bool
}

func (v NullableGetTransactionResponse) Get() *GetTransactionResponse {
	return v.value
}

func (v *NullableGetTransactionResponse) Set(val *GetTransactionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTransactionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTransactionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTransactionResponse(val *GetTransactionResponse) *NullableGetTransactionResponse {
	return &NullableGetTransactionResponse{value: val, isSet: true}
}

func (v NullableGetTransactionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTransactionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


