/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
)

// checks if the When type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &When{}

// When Wait for an action to be performed and apply the matching contract when it does. Apply the timeout contract if no actions have been performed in the timeout period.
type When struct {
	Timeout int64 `json:"timeout"`
	TimeoutContinuation Contract `json:"timeout_continuation"`
	When []Case `json:"when"`
}

// NewWhen instantiates a new When object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhen(timeout int64, timeoutContinuation Contract, when []Case) *When {
	this := When{}
	this.Timeout = timeout
	this.TimeoutContinuation = timeoutContinuation
	this.When = when
	return &this
}

// NewWhenWithDefaults instantiates a new When object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhenWithDefaults() *When {
	this := When{}
	return &this
}

// GetTimeout returns the Timeout field value
func (o *When) GetTimeout() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Timeout
}

// GetTimeoutOk returns a tuple with the Timeout field value
// and a boolean to check if the value has been set.
func (o *When) GetTimeoutOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timeout, true
}

// SetTimeout sets field value
func (o *When) SetTimeout(v int64) {
	o.Timeout = v
}

// GetTimeoutContinuation returns the TimeoutContinuation field value
func (o *When) GetTimeoutContinuation() Contract {
	if o == nil {
		var ret Contract
		return ret
	}

	return o.TimeoutContinuation
}

// GetTimeoutContinuationOk returns a tuple with the TimeoutContinuation field value
// and a boolean to check if the value has been set.
func (o *When) GetTimeoutContinuationOk() (*Contract, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TimeoutContinuation, true
}

// SetTimeoutContinuation sets field value
func (o *When) SetTimeoutContinuation(v Contract) {
	o.TimeoutContinuation = v
}

// GetWhen returns the When field value
func (o *When) GetWhen() []Case {
	if o == nil {
		var ret []Case
		return ret
	}

	return o.When
}

// GetWhenOk returns a tuple with the When field value
// and a boolean to check if the value has been set.
func (o *When) GetWhenOk() ([]Case, bool) {
	if o == nil {
		return nil, false
	}
	return o.When, true
}

// SetWhen sets field value
func (o *When) SetWhen(v []Case) {
	o.When = v
}

func (o When) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o When) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["timeout"] = o.Timeout
	toSerialize["timeout_continuation"] = o.TimeoutContinuation
	toSerialize["when"] = o.When
	return toSerialize, nil
}

type NullableWhen struct {
	value *When
	isSet bool
}

func (v NullableWhen) Get() *When {
	return v.value
}

func (v *NullableWhen) Set(val *When) {
	v.value = val
	v.isSet = true
}

func (v NullableWhen) IsSet() bool {
	return v.isSet
}

func (v *NullableWhen) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhen(val *When) *NullableWhen {
	return &NullableWhen{value: val, isSet: true}
}

func (v NullableWhen) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhen) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


