/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
)

// checks if the NotifyAction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NotifyAction{}

// NotifyAction struct for NotifyAction
type NotifyAction struct {
	NotifyIf Observation `json:"notify_if"`
}

// NewNotifyAction instantiates a new NotifyAction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotifyAction(notifyIf Observation) *NotifyAction {
	this := NotifyAction{}
	this.NotifyIf = notifyIf
	return &this
}

// NewNotifyActionWithDefaults instantiates a new NotifyAction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotifyActionWithDefaults() *NotifyAction {
	this := NotifyAction{}
	return &this
}

// GetNotifyIf returns the NotifyIf field value
func (o *NotifyAction) GetNotifyIf() Observation {
	if o == nil {
		var ret Observation
		return ret
	}

	return o.NotifyIf
}

// GetNotifyIfOk returns a tuple with the NotifyIf field value
// and a boolean to check if the value has been set.
func (o *NotifyAction) GetNotifyIfOk() (*Observation, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NotifyIf, true
}

// SetNotifyIf sets field value
func (o *NotifyAction) SetNotifyIf(v Observation) {
	o.NotifyIf = v
}

func (o NotifyAction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NotifyAction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["notify_if"] = o.NotifyIf
	return toSerialize, nil
}

type NullableNotifyAction struct {
	value *NotifyAction
	isSet bool
}

func (v NullableNotifyAction) Get() *NotifyAction {
	return v.value
}

func (v *NullableNotifyAction) Set(val *NotifyAction) {
	v.value = val
	v.isSet = true
}

func (v NullableNotifyAction) IsSet() bool {
	return v.isSet
}

func (v *NullableNotifyAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotifyAction(val *NotifyAction) *NullableNotifyAction {
	return &NullableNotifyAction{value: val, isSet: true}
}

func (v NullableNotifyAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotifyAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


