/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
)

// checks if the IfObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IfObject{}

// IfObject If an observation is true, the first contract applies, otherwise the second contract applies.
type IfObject struct {
	Else ContractObject `json:"else"`
	If ObservationObject `json:"if"`
	Then ContractObject `json:"then"`
}

// NewIfObject instantiates a new IfObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIfObject(else_ ContractObject, if_ ObservationObject, then ContractObject) *IfObject {
	this := IfObject{}
	this.Else = else_
	this.If = if_
	this.Then = then
	return &this
}

// NewIfObjectWithDefaults instantiates a new IfObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIfObjectWithDefaults() *IfObject {
	this := IfObject{}
	return &this
}

// GetElse returns the Else field value
func (o *IfObject) GetElse() ContractObject {
	if o == nil {
		var ret ContractObject
		return ret
	}

	return o.Else
}

// GetElseOk returns a tuple with the Else field value
// and a boolean to check if the value has been set.
func (o *IfObject) GetElseOk() (*ContractObject, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Else, true
}

// SetElse sets field value
func (o *IfObject) SetElse(v ContractObject) {
	o.Else = v
}

// GetIf returns the If field value
func (o *IfObject) GetIf() ObservationObject {
	if o == nil {
		var ret ObservationObject
		return ret
	}

	return o.If
}

// GetIfOk returns a tuple with the If field value
// and a boolean to check if the value has been set.
func (o *IfObject) GetIfOk() (*ObservationObject, bool) {
	if o == nil {
		return nil, false
	}
	return &o.If, true
}

// SetIf sets field value
func (o *IfObject) SetIf(v ObservationObject) {
	o.If = v
}

// GetThen returns the Then field value
func (o *IfObject) GetThen() ContractObject {
	if o == nil {
		var ret ContractObject
		return ret
	}

	return o.Then
}

// GetThenOk returns a tuple with the Then field value
// and a boolean to check if the value has been set.
func (o *IfObject) GetThenOk() (*ContractObject, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Then, true
}

// SetThen sets field value
func (o *IfObject) SetThen(v ContractObject) {
	o.Then = v
}

func (o IfObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IfObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["else"] = o.Else
	toSerialize["if"] = o.If
	toSerialize["then"] = o.Then
	return toSerialize, nil
}

type NullableIfObject struct {
	value *IfObject
	isSet bool
}

func (v NullableIfObject) Get() *IfObject {
	return v.value
}

func (v *NullableIfObject) Set(val *IfObject) {
	v.value = val
	v.isSet = true
}

func (v NullableIfObject) IsSet() bool {
	return v.isSet
}

func (v *NullableIfObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIfObject(val *IfObject) *NullableIfObject {
	return &NullableIfObject{value: val, isSet: true}
}

func (v NullableIfObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIfObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


