/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
)

// checks if the PartialPayment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartialPayment{}

// PartialPayment A warning for partial payment.
type PartialPayment struct {
	Account Party `json:"account"`
	AskedToPay int32 `json:"asked_to_pay"`
	ButOnlyPaid int32 `json:"but_only_paid"`
	OfToken Token `json:"of_token"`
	ToPayee Payee `json:"to_payee"`
}

// NewPartialPayment instantiates a new PartialPayment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartialPayment(account Party, askedToPay int32, butOnlyPaid int32, ofToken Token, toPayee Payee) *PartialPayment {
	this := PartialPayment{}
	this.Account = account
	this.AskedToPay = askedToPay
	this.ButOnlyPaid = butOnlyPaid
	this.OfToken = ofToken
	this.ToPayee = toPayee
	return &this
}

// NewPartialPaymentWithDefaults instantiates a new PartialPayment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartialPaymentWithDefaults() *PartialPayment {
	this := PartialPayment{}
	return &this
}

// GetAccount returns the Account field value
func (o *PartialPayment) GetAccount() Party {
	if o == nil {
		var ret Party
		return ret
	}

	return o.Account
}

// GetAccountOk returns a tuple with the Account field value
// and a boolean to check if the value has been set.
func (o *PartialPayment) GetAccountOk() (*Party, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Account, true
}

// SetAccount sets field value
func (o *PartialPayment) SetAccount(v Party) {
	o.Account = v
}

// GetAskedToPay returns the AskedToPay field value
func (o *PartialPayment) GetAskedToPay() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AskedToPay
}

// GetAskedToPayOk returns a tuple with the AskedToPay field value
// and a boolean to check if the value has been set.
func (o *PartialPayment) GetAskedToPayOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AskedToPay, true
}

// SetAskedToPay sets field value
func (o *PartialPayment) SetAskedToPay(v int32) {
	o.AskedToPay = v
}

// GetButOnlyPaid returns the ButOnlyPaid field value
func (o *PartialPayment) GetButOnlyPaid() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ButOnlyPaid
}

// GetButOnlyPaidOk returns a tuple with the ButOnlyPaid field value
// and a boolean to check if the value has been set.
func (o *PartialPayment) GetButOnlyPaidOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ButOnlyPaid, true
}

// SetButOnlyPaid sets field value
func (o *PartialPayment) SetButOnlyPaid(v int32) {
	o.ButOnlyPaid = v
}

// GetOfToken returns the OfToken field value
func (o *PartialPayment) GetOfToken() Token {
	if o == nil {
		var ret Token
		return ret
	}

	return o.OfToken
}

// GetOfTokenOk returns a tuple with the OfToken field value
// and a boolean to check if the value has been set.
func (o *PartialPayment) GetOfTokenOk() (*Token, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OfToken, true
}

// SetOfToken sets field value
func (o *PartialPayment) SetOfToken(v Token) {
	o.OfToken = v
}

// GetToPayee returns the ToPayee field value
func (o *PartialPayment) GetToPayee() Payee {
	if o == nil {
		var ret Payee
		return ret
	}

	return o.ToPayee
}

// GetToPayeeOk returns a tuple with the ToPayee field value
// and a boolean to check if the value has been set.
func (o *PartialPayment) GetToPayeeOk() (*Payee, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ToPayee, true
}

// SetToPayee sets field value
func (o *PartialPayment) SetToPayee(v Payee) {
	o.ToPayee = v
}

func (o PartialPayment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartialPayment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account"] = o.Account
	toSerialize["asked_to_pay"] = o.AskedToPay
	toSerialize["but_only_paid"] = o.ButOnlyPaid
	toSerialize["of_token"] = o.OfToken
	toSerialize["to_payee"] = o.ToPayee
	return toSerialize, nil
}

type NullablePartialPayment struct {
	value *PartialPayment
	isSet bool
}

func (v NullablePartialPayment) Get() *PartialPayment {
	return v.value
}

func (v *NullablePartialPayment) Set(val *PartialPayment) {
	v.value = val
	v.isSet = true
}

func (v NullablePartialPayment) IsSet() bool {
	return v.isSet
}

func (v *NullablePartialPayment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartialPayment(val *PartialPayment) *NullablePartialPayment {
	return &NullablePartialPayment{value: val, isSet: true}
}

func (v NullablePartialPayment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartialPayment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


