/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
)

// checks if the GetWithdrawalsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetWithdrawalsResponse{}

// GetWithdrawalsResponse struct for GetWithdrawalsResponse
type GetWithdrawalsResponse struct {
	Results []GetWithdrawalsResponseResultsInner `json:"results"`
}

// NewGetWithdrawalsResponse instantiates a new GetWithdrawalsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetWithdrawalsResponse(results []GetWithdrawalsResponseResultsInner) *GetWithdrawalsResponse {
	this := GetWithdrawalsResponse{}
	this.Results = results
	return &this
}

// NewGetWithdrawalsResponseWithDefaults instantiates a new GetWithdrawalsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetWithdrawalsResponseWithDefaults() *GetWithdrawalsResponse {
	this := GetWithdrawalsResponse{}
	return &this
}

// GetResults returns the Results field value
func (o *GetWithdrawalsResponse) GetResults() []GetWithdrawalsResponseResultsInner {
	if o == nil {
		var ret []GetWithdrawalsResponseResultsInner
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *GetWithdrawalsResponse) GetResultsOk() ([]GetWithdrawalsResponseResultsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *GetWithdrawalsResponse) SetResults(v []GetWithdrawalsResponseResultsInner) {
	o.Results = v
}

func (o GetWithdrawalsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetWithdrawalsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["results"] = o.Results
	return toSerialize, nil
}

type NullableGetWithdrawalsResponse struct {
	value *GetWithdrawalsResponse
	isSet bool
}

func (v NullableGetWithdrawalsResponse) Get() *GetWithdrawalsResponse {
	return v.value
}

func (v *NullableGetWithdrawalsResponse) Set(val *GetWithdrawalsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetWithdrawalsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetWithdrawalsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetWithdrawalsResponse(val *GetWithdrawalsResponse) *NullableGetWithdrawalsResponse {
	return &NullableGetWithdrawalsResponse{value: val, isSet: true}
}

func (v NullableGetWithdrawalsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetWithdrawalsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


