/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
)

// checks if the GetContractResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetContractResponse{}

// GetContractResponse struct for GetContractResponse
type GetContractResponse struct {
	Links GetContractResponseLinks `json:"links"`
	Resource ContractState `json:"resource"`
}

// NewGetContractResponse instantiates a new GetContractResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetContractResponse(links GetContractResponseLinks, resource ContractState) *GetContractResponse {
	this := GetContractResponse{}
	this.Links = links
	this.Resource = resource
	return &this
}

// NewGetContractResponseWithDefaults instantiates a new GetContractResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetContractResponseWithDefaults() *GetContractResponse {
	this := GetContractResponse{}
	return &this
}

// GetLinks returns the Links field value
func (o *GetContractResponse) GetLinks() GetContractResponseLinks {
	if o == nil {
		var ret GetContractResponseLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *GetContractResponse) GetLinksOk() (*GetContractResponseLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *GetContractResponse) SetLinks(v GetContractResponseLinks) {
	o.Links = v
}

// GetResource returns the Resource field value
func (o *GetContractResponse) GetResource() ContractState {
	if o == nil {
		var ret ContractState
		return ret
	}

	return o.Resource
}

// GetResourceOk returns a tuple with the Resource field value
// and a boolean to check if the value has been set.
func (o *GetContractResponse) GetResourceOk() (*ContractState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Resource, true
}

// SetResource sets field value
func (o *GetContractResponse) SetResource(v ContractState) {
	o.Resource = v
}

func (o GetContractResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetContractResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["links"] = o.Links
	toSerialize["resource"] = o.Resource
	return toSerialize, nil
}

type NullableGetContractResponse struct {
	value *GetContractResponse
	isSet bool
}

func (v NullableGetContractResponse) Get() *GetContractResponse {
	return v.value
}

func (v *NullableGetContractResponse) Set(val *GetContractResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetContractResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetContractResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetContractResponse(val *GetContractResponse) *NullableGetContractResponse {
	return &NullableGetContractResponse{value: val, isSet: true}
}

func (v NullableGetContractResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetContractResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


