/*
Marlowe Runtime REST API

REST API for Marlowe Runtime

API version: 0.0.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marloweruntime

import (
	"encoding/json"
)

// checks if the GetPayoutsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPayoutsResponse{}

// GetPayoutsResponse struct for GetPayoutsResponse
type GetPayoutsResponse struct {
	Results []GetPayoutsResponseResultsInner `json:"results"`
}

// NewGetPayoutsResponse instantiates a new GetPayoutsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPayoutsResponse(results []GetPayoutsResponseResultsInner) *GetPayoutsResponse {
	this := GetPayoutsResponse{}
	this.Results = results
	return &this
}

// NewGetPayoutsResponseWithDefaults instantiates a new GetPayoutsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPayoutsResponseWithDefaults() *GetPayoutsResponse {
	this := GetPayoutsResponse{}
	return &this
}

// GetResults returns the Results field value
func (o *GetPayoutsResponse) GetResults() []GetPayoutsResponseResultsInner {
	if o == nil {
		var ret []GetPayoutsResponseResultsInner
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *GetPayoutsResponse) GetResultsOk() ([]GetPayoutsResponseResultsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *GetPayoutsResponse) SetResults(v []GetPayoutsResponseResultsInner) {
	o.Results = v
}

func (o GetPayoutsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPayoutsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["results"] = o.Results
	return toSerialize, nil
}

type NullableGetPayoutsResponse struct {
	value *GetPayoutsResponse
	isSet bool
}

func (v NullableGetPayoutsResponse) Get() *GetPayoutsResponse {
	return v.value
}

func (v *NullableGetPayoutsResponse) Set(val *GetPayoutsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPayoutsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPayoutsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPayoutsResponse(val *GetPayoutsResponse) *NullableGetPayoutsResponse {
	return &NullableGetPayoutsResponse{value: val, isSet: true}
}

func (v NullableGetPayoutsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPayoutsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


